iou rest service
iSFomin/IouRestService pull request #1
Opened 2021-11-09 10:39 UTC by iSFomin

Добавлены:
- rest-controllers;
- services;
- entities;
- dto;
- converters;
- configuration;
- liquibase changelog;
- unit tests.

[Примеры и описание API](https://github.com/iSFomin/IouRestService/blob/master/README.md)

2021-11-09 10:45 UTC, iSFomin commented
Что отправлять в ответ на операции добавления (POST)...
Id добавленной записи?
Добавленную сущность целиком (в моей реализации)?
Код 200 с текстом в теле что-то типа "добавлено успешно"?
Код 200 с пустым ответом?
Есть общие стандарты или правила хорошего тона или всё зависит от контекста задачи?

2021-11-09 11:12 UTC, iSFomin commented on src/main/kotlin/com/codereview/iou/service/PromissoryNoteService.kt
> +            .reduce { _, accumulator, element ->
плохо представляю как работает aggregate функция
хотелось бы reduce и map объединить во что-то... с помощью aggregate возможно так сделать?

2021-11-09 11:16 UTC, iSFomin commented on src/main/kotlin/com/codereview/iou/service/PromissoryNoteService.kt
> +            .reduce { _, accumulator, element ->
хотелось бы на примерах увидеть как можно сократить количество операций в этом коде

2021-11-11 10:57 UTC, YourCodeReview commented
Ссылка на задание:

https://t.me/try2py/197

2021-11-13 10:58 UTC, iSFomin commented on src/main/kotlin/com/codereview/iou/service/PromissoryNoteService.kt
> +        if (validatePromissoryNoteEntity(promissoryNote)) {
данные полученный от пользователя правильнее валидировать в объекте dto или в entity?

2021-11-14 13:16 UTC, MardokUA requested changes

2021-11-14 13:16 UTC, MardokUA commented on build.gradle.kts
> +	implementation("org.springframework.boot:spring-boot-starter:2.5.6")
я бы советовал выносить общие версии зависиомтсей в переменные. 
```suggestion
        val spring = "2.5.6"
	implementation("org.springframework.boot:spring-boot-starter:$spring")
```

2021-11-14 13:16 UTC, MardokUA commented on src/main/kotlin/com/codereview/iou/controller/IouController.kt
> +    lateinit var service: PromissoryNoteService
Я не знаком с Spring и как он доставляет зависимости, но, если можно, я бы организовывал DI в конструктор а не в свойство класса. Самый большой плюс - в тестах можно отказаться от фреймворка и самому мокать классы

2021-11-14 13:16 UTC, MardokUA commented on src/main/kotlin/com/codereview/iou/controller/IouController.kt
> +    fun getAllIou(): PromissoryNotesDto {
Более идиомично писать вот так:
```suggestion
    fun getAllIou(): PromissoryNotesDto = service.listPromissoryNotes()
```

2021-11-14 13:16 UTC, MardokUA commented on src/main/kotlin/com/codereview/iou/controller/IouController.kt
> +        service.deletePromissoryNote(promissoryNoteDto)
Вот тут не совсем понятно - а чтоесли удалить не получиться? Все равно нуно возвращать success?

2021-11-14 13:16 UTC, MardokUA commented on src/main/kotlin/com/codereview/iou/controller/UserController.kt
> +        service.deleteUser(userDto)
Тот же самый вопрос. Я поддерживаю следующих подход - если функция выполняет действие над базой данных, то всегда должен быть тип возвращаемого значение. Например, для вставки это `Int` в качестве количесва записей или массив  `long`в качестве массива IDшников. Тут вероятно подойдет даже `boolean`

2021-11-14 13:16 UTC, MardokUA commented on src/main/kotlin/com/codereview/iou/controller/handler/RestResponseEntityExceptionHandler.kt
> +            ExceptionDto(ex.message ?: ex.toString()), HttpHeaders(), HttpStatus.BAD_REQUEST
Правильный подход работы с ошибками, когда нужно обернуть ошибку системы в свою, это положить реальную ошибку в `cause` своей кастомной ошибки. Я понимаю, что Вы возвращаете DTO, однако держа все вышесказанное в голове, я бы в текст ошибки ложил бы `ex.message() ?: ex?.cause?.message ?: ex.toString()`

2021-11-14 13:16 UTC, MardokUA commented on src/main/kotlin/com/codereview/iou/model/dto/ExceptionDto.kt
> +class ExceptionDto(val error: String)
Советовал бы для такой задачи использовать `inline/value class`, в зависимости от версии Kotlin

2021-11-14 13:16 UTC, MardokUA commented on src/main/kotlin/com/codereview/iou/model/dto/PromissoryNoteCreateDto.kt
> +class PromissoryNoteCreateDto() {
Есть ли смысл использовать `data class`?

2021-11-14 13:16 UTC, MardokUA commented on src/main/kotlin/com/codereview/iou/model/dto/UserDto.kt
> +class UserDto() {
Мне кажется, что все `DTO` классы можно смело делать `data class`

2021-11-14 13:16 UTC, MardokUA commented on src/main/kotlin/com/codereview/iou/model/entity/PromissoryNote.kt
> +    @Column(nullable = false)
Повторюсь, что не знаком со Spring, но выглядит очень комично - nullable поле которое не может быть null)

2021-11-14 13:16 UTC, MardokUA commented on src/main/kotlin/com/codereview/iou/service/PromissoryNoteService.kt
> +    lateinit var iouRepository: PromissoryNoteRepository
опять же вопрос о `lateinit` - я предпочитаю injection в конструктор а не в поля. `lateinit` вообще считается огромной ошибкой в Kotlin. Это говорил сам Андрей Бреслав и для этих целей есть` Delegates.notNull()`

2021-11-14 13:16 UTC, MardokUA commented on src/main/kotlin/com/codereview/iou/service/PromissoryNoteService.kt
> +        val promissoryNote = PromissoryNote().apply {
почему бы сразу не создать инстас класса и не положить все в конструктор? Теперь я понимаю зачем Вам nullable поля. Я все же настаиваю на `data class` и `not null property` внутри. В котлине есть именованные аргументы, что позволяет избежать проблемы изменения положения свойств в конструкторе. Пологаю, именно с этой целью вы используете `apply` как замену паттерна `Builder`

2021-11-14 13:16 UTC, MardokUA commented on src/main/kotlin/com/codereview/iou/service/PromissoryNoteService.kt
> +        if (validatePromissoryNoteEntity(promissoryNote)) {
К сежелению, я не back-end'щик и поэтому сказать как правильно с точки зрения такого разработчика я не могу. Однако, с точки зрения Clean Architecture, у меня ответ такой:
- если `PromissoryNoteService` часть `domain`слоя, то перед мапингом
- если часть `data` слоя, то вообще не здесь, а в `domain` слое

2021-11-14 13:16 UTC, MardokUA commented on src/main/kotlin/com/codereview/iou/service/UserService.kt
> +            throw IllegalArgumentException("Entity {$user} not valid.")
Я бы советовал написать inline функцию, что-то вроде `validate(block: () -> Boolean, exp: <тип ошибки>})` и перегрузил бы его.

2021-11-14 13:16 UTC, MardokUA commented on src/main/kotlin/com/codereview/iou/service/UserService.kt
> +        return converter.convertToDto(user)
```suggestion
        return epository.findById(userId).get().run {converter.convertToDto(this)}
```

2021-11-14 13:16 UTC, MardokUA commented on src/test/kotlin/com/codereview/iou/service/PromissoryNoteServiceTest.kt
> +    fun getNotExistPromissoryNote() {
Советую испоьзовать кричащие наименования функций и использовать Геркин (https://ru.wikipedia.org/wiki/BDD_(%D0%BF%D1%80%D0%BE%D0%B3%D1%80%D0%B0%D0%BC%D0%BC%D0%B8%D1%80%D0%BE%D0%B2%D0%B0%D0%BD%D0%B8%D0%B5))
пример, как переименовать этот тест: 
```suggestion
    fun `when note id is invalid, error should be returned`() {
```

2021-11-14 14:45 UTC, iSFomin commented on src/main/kotlin/com/codereview/iou/service/PromissoryNoteService.kt
> +        if (validatePromissoryNoteEntity(promissoryNote)) {
На самом деле я тоже не бэкенд разработчик, практикую котлин)
Clean Architecture да, спасибо, попробую углубится в этот вопрос.

2021-11-14 14:50 UTC, iSFomin commented on src/main/kotlin/com/codereview/iou/controller/IouController.kt
> +        service.deletePromissoryNote(promissoryNoteDto)
На самом деле меня бы тоже смутил этот код. В спринге есть Exception Handler, если вдруг что-то пойдёт не так при удалении - выкинется исключение, отработает Exception Handler и ветка исполнения пойдет мимо "success".

2021-11-14 14:53 UTC, iSFomin commented on src/main/kotlin/com/codereview/iou/controller/IouController.kt
> +        service.deletePromissoryNote(promissoryNoteDto)
Так я думал что работает...
Но пытаюсь проверить и ведь реально "success" во всех случаях, кроме id = null который я явно обрабатываю

2021-11-14 15:01 UTC, iSFomin commented on src/main/kotlin/com/codereview/iou/service/PromissoryNoteService.kt
> +        val promissoryNote = PromissoryNote().apply {
1. data class не рекомендуется устанавливать для JPA сущности. Предопредление от идеи: The data class implementations of equals(), hashCode() and toString() are not recommended for JPA entities. They can cause severe performance and memory consumption issues. 
2. перенести параметры в конструктор, в общем то ничего не мешает, можно попробовать

2021-11-14 15:04 UTC, iSFomin commented on src/main/kotlin/com/codereview/iou/service/UserService.kt
> +            throw IllegalArgumentException("Entity {$user} not valid.")
Хорошее замечание, учту)

2021-11-14 15:05 UTC, iSFomin commented on src/test/kotlin/com/codereview/iou/service/PromissoryNoteServiceTest.kt
> +    fun getNotExistPromissoryNote() {
В первые об этом слышу, спасибо)

2021-11-14 15:10 UTC, iSFomin commented on src/main/kotlin/com/codereview/iou/controller/UserController.kt
> +        service.deleteUser(userDto)
spring data jpa для методов delete возвращает void, поэтому приходится полагаться на эксепшены
заменить текст "success" на количество удаленных записей, возможно да, так будет более информативно

2021-11-18 19:27 UTC, merged